name: shelter_partner
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+9

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_functions: ^5.1.3
  http: ^1.2.2
  cloud_firestore: ^5.4.3
  provider: ^6.1.2
  csv: ^5.0.0
  uuid: ^4.1.0
  flutter_riverpod: ^2.5.1
  flutter_markdown: ^0.7.1
  riverpod_annotation: ^2.3.5
  fluttertoast: ^8.2.8
  geolocator: ^10.1.0
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.1
  go_router: ^14.3.0
  email_validator: ^2.0.1
  cached_network_image: ^3.4.1
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.3+2
  url_launcher: ^6.1.7
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  package_info_plus: ^8.1.0
  infinite_scroll_pagination: ^4.0.0
  cupertino_icons: ^1.0.8
  qonversion_flutter: ^9.1.5
  auto_size_text: ^3.0.0
  icon_decoration: ^2.1.0
  fl_chart: ^0.69.2
  rxdart: ^0.28.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1



dependency_overrides:
  geolocator_android: 4.6.1
  google_maps_flutter_web: ^0.5.6  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/csv/

  fonts:
    - family: CabinBold
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
    - family: CabinRegular
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
